= Kubernetes for Windows Developers Demo: Setup =
:experimental:
:imagesdir: docs/images
:toc:
:toclevels: 4

== Installing Demo ==
[IMPORTANT]
====
* Before running any script commands, make sure the run the following in the appropriate shell.  Note that the first parameter in this command will set the `PROJECT_PREFIX` environment variable which is referenced in many of the instructions.  If not provided, the default is `demo-dev`.
+
----
. scripts/shell-setup.sh 
----
====

=== Setup Prerequisites ===

. Setup your environment or shell variables as outlined <<Variables Used in This Demo,here>>
. Run the following script to install the necessary operators to your cluster
+
----
$DEMO_HOME/scripts/install-prereq.sh
----

==== Cluster Installation ====

See also instructons link:https://docs.openshift.com/container-platform/4.5/installing/installing_azure/installing-azure-network-customizations.html[here] and link:https://github.com/openshift/cluster-network-operator#configuring-ovnkubernetes-on-a-hybrid-cluster[here]

. Download the openshift installer for Azure
. Use the link:install/openshift-installer/install-config.yaml[install-config.yaml] as a reference to create the cluster.  
. Create Manifest files using the command
+
----
./openshift-install create manifests
----
+
. Copy the link:install/openshift-installer/cluster-network-03-config.yaml[cluster-network-03-config.yaml] into the `manifest` subdirectory
** This configures the cluster network operator to allow hybrid networking so that linux and windows nodes can co-exist in the cluster
. Continue with the installation process as normal

=== Main Demo Installation ===

. Install the main part of the demo by running this command
** NOTE: `-p` is optional and `-i` installs prerequisites
+
----
$DEMO_HOME/scripts/create-demo.sh -p $PROJECT_PREFIX -i
----

== Appendix ==

=== Connecting to a Windows VM via RDP ===

You can always connect to a Windows VM via the built-in VNC console.  However, if you want to connect externally via and RDP client here is one way this can be done.

. Enable RDP on the Windows instance itself by following the steps in link:https://computingforgeeks.com/how-to-enable-remote-desktop-protocol-rdp-on-windows-server-2019/[this article]
. Run the following commands in a PowerShell running as `Administrator`:
+
----
Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyT
SConnections" -value 0

Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
----
+
. Create a loadbalancer service, as can be found link:install/vms/rdp-svc.yaml[here] by running this command
** See also link:https://medium.com/cooking-with-azure/using-kubevirt-in-azure-kubernetes-service-part-3-windows-vm-363d6b653d7[this article] for more information about this
+
----
oc apply -f $DEMO_HOME/install/vms/rdp-svc.yaml -n $PROJECT_PREFIX-vm
----

=== Creating an image from a OpenShift Virtualization Windows VM ===

. Set the virtual machine to stopped (in Kubernetes)
. In the windows VM, run the following command:
** See also link:https://devopspoints.com/windows-server-2019-enabling-quick-server-rollouts-with-sysprep.html[this article]
+
----
C:\Windows\System32\Sysprep\sysprep.exe
----
+
. You can configure from the UI like this:
** OOBE
** Generate
** Shutdown
. When the VM is done it will shutdown and when that happens, k8 should terminate the pod
. Find the PVC that represents the disk that was just sysprepped
. Configure the link:install/kube/tekton/taskrun/copy-img-run.yaml[Copy Image TaskRun] to fish the .img out of the PVC and upload to s3
. You can now use that .img in a new virtual machine
** NOTE: When the new virtual machine boots up, a couple initial things will need to be configured (like accounts and locale)

=== Exposing a route to a specific port on the VM ===

To expose traffic to a given port on a vm, you can do the following (after you ensure that Windows firewall has an inbound rule for that port)

. Run the following command
** *target-port* this is the port on the VM that you are trying to expose
** *port* this is the port that the service listens on
+
----
virtctl expose vmi win-2019-vm --port=8080 --target-port=80 --name=iis-service
----
+
. Double check the service to make sure the pod selector is picking up the correct vm-launcher pod that represents the vm
+
. Then expose the svc as you would normally to create a route
+
----
oc expose svc/iis-service
----

=== Windows Machine Config Operator Build

