apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hplus-db
    app.kubernetes.io/component: hplus-db
    app.kubernetes.io/instance: hplus-db
    app.kubernetes.io/part-of: hplus-db
    app.openshift.io/runtime: mssql
  name: hplus-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hplus-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hplus-db
        deploymentconfig: hplus-db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        envFrom:
        - secretRef:
            name: sql-secret
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        name: hplus-db
        ports:
        - containerPort: 1433
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hplus-db
  labels:
    app: hplus-db
    app.kubernetes.io/component: hplus-db
    app.kubernetes.io/instance: hplus-db
    app.kubernetes.io/part-of: hplus-db
    app.openshift.io/runtime: mssql
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: hplus-db
  sessionAffinity: None
  type: ClusterIP