apiVersion: v1
kind: ServiceAccount
metadata:
 name: events-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: event-watcher
rules:
 - apiGroups:
     - ""
   resources:
     - nodes
   verbs:
     - get
     - list
     - watch
