apiVersion: v1
baseDomain: azure.openshifttc.com
kind: kustomization
metadata:
  name: cbrwin-ocp46
controlPlane:
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 256
        diskType: ""
      type: Standard_D2s_v3
  replicas: 3