apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-viewer
rules:
- apiGroups:
  - "machine.openshift.io"
  resources:
  - machines
  verbs:
  - get
  - list
  - watch