apiVersion: v1
kind: Service
metadata:
  name: win-2019-webdeploy
spec:
  ports:
  - port: 8172
    name: webdeploy
    protocol: TCP
    targetPort: 8172
  - port: 80
    name: msdep
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt.io/domain: win-2019
    vm.kubevirt.io/name: win-2019-vm
  sessionAffinity: None
  type: LoadBalancer
