# FIXME: Cluster would work better with the following due to memory requirements
# Masters: Standard_D2_v3
# Workers: Standard_D4_v3

apiVersion: v1
baseDomain: azure.openshifttc.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: Standard_D2s_v3
      osDisk:
        diskSizeGB: 512 
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: Standard_D4s_v3
      osDisk:
        diskSizeGB: 512 
  replicas: 3
metadata:
  creationTimestamp: null
  name: cbrwin-46
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  # OVNKubernetes networking is critical for supporting windows node networking
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: k84windev
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: australiasoutheast
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K21oaWxkZW5icmVkaGF0Y29tMXp5ZHZ5d2dtY29ib2p6MGRla2Nnb3U3NmVuOko1SDJHVzE3VE5BNVBXQUc3S0VKT0Y4UjVZS0lVMllJOUdMMkszVTBaWjEzVEhXVVRJVlVCU0NDUkgzRE1ZQzg=","email":"mhildenb@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K21oaWxkZW5icmVkaGF0Y29tMXp5ZHZ5d2dtY29ib2p6MGRla2Nnb3U3NmVuOko1SDJHVzE3VE5BNVBXQUc3S0VKT0Y4UjVZS0lVMllJOUdMMkszVTBaWjEzVEhXVVRJVlVCU0NDUkgzRE1ZQzg=","email":"mhildenb@redhat.com"},"registry.connect.redhat.com":{"auth":"NTMzMTE2MTF8dWhjLTFaeWRWWXdnbUNvYm9KWjBkZWtjZ291NzZFbjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBaV0psWVRGbE5EUXpOelEwT0RFMk9HTTNZVEJsTWpWbU9XUmhNRE01T0NKOS5DRFJxcndQZ3JaSzRBMzRudFpwb00zUXFfemE3cENKTzNvMnVXazhRVzd4bEZnUFdNOVB0LUpPUDd6czFHcTdfMkt0ZGVLMk5JT2p3djRmUi12WG9IV3RjNjB4ZUg0R3NaYnBlVzBobC0yZjFQVmk1VWZ3d19mSmFJSFBSNkphYVRiUnl2WGx0anZKclhZd0g1OG5LUzB2VGhXNW9QQ0VWY1oydjF0V1pSM2xpbFA2OW91bmhkN2lfa3dLVXNDN3o5TVNIVFFrV1lMaTJ6dDFLTE82UTNqZGZZS0tfNjk2TmdvdktkdHBqUjhiQTJ3dFVyOVUzSmFTN1JkWTg0N0F6SVMyYjQ4Y2dQbnlobllaQzFjTDdmLU1YN0RMTVZsM1NzMWdPdDhaNVFCa3o3NVl1dXN5SDk3bF9YSl96TUhnWHJkWUtIcGhPbGFGRmU5b3VWc2t2Y05pZE1XVlpZUGdnMVhHaTdWMWZKUXJwUjVHWmFPS1NxR3lhQk56M3RtVVcxRWxsdl9mUTlCX3JrV3JXbUplWVZsSElrS2hPTWZWcXNMb1FkeDNJcXZsNWpLMWg2elc3QzcyeG1OdUUwVGotbEM1ZTA4VmMtU0JWMUFKV3R4T0JmRUVvNnFwZXhpVDRYWWlSMXhvamJfeHBKWjdXQTUxQl9jU0c1UWJDVFpHZGZvcm8zc3oxYWVyeDMzUUFkdVpoRXR6ZEJ0SzN6SERLaWd6dERQY0RXTzViLThpR0dzY05tX2ZqNU9oWXRnTlBzbGtKNERoQkNOVHFKY1V0OTVLeDZUUmstSk9saW9tNTFnZUYwSkJBMk5HQnU0UXlzMFpyY2M0V1hTUWM3RU5FeDY2d0FJc1RpSFk1clVPNzRqTHF2YUYzOENMek5mak1HYlFFWVYwaFBnZw==","email":"mhildenb@redhat.com"},"registry.redhat.io":{"auth":"NTMzMTE2MTF8dWhjLTFaeWRWWXdnbUNvYm9KWjBkZWtjZ291NzZFbjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBaV0psWVRGbE5EUXpOelEwT0RFMk9HTTNZVEJsTWpWbU9XUmhNRE01T0NKOS5DRFJxcndQZ3JaSzRBMzRudFpwb00zUXFfemE3cENKTzNvMnVXazhRVzd4bEZnUFdNOVB0LUpPUDd6czFHcTdfMkt0ZGVLMk5JT2p3djRmUi12WG9IV3RjNjB4ZUg0R3NaYnBlVzBobC0yZjFQVmk1VWZ3d19mSmFJSFBSNkphYVRiUnl2WGx0anZKclhZd0g1OG5LUzB2VGhXNW9QQ0VWY1oydjF0V1pSM2xpbFA2OW91bmhkN2lfa3dLVXNDN3o5TVNIVFFrV1lMaTJ6dDFLTE82UTNqZGZZS0tfNjk2TmdvdktkdHBqUjhiQTJ3dFVyOVUzSmFTN1JkWTg0N0F6SVMyYjQ4Y2dQbnlobllaQzFjTDdmLU1YN0RMTVZsM1NzMWdPdDhaNVFCa3o3NVl1dXN5SDk3bF9YSl96TUhnWHJkWUtIcGhPbGFGRmU5b3VWc2t2Y05pZE1XVlpZUGdnMVhHaTdWMWZKUXJwUjVHWmFPS1NxR3lhQk56M3RtVVcxRWxsdl9mUTlCX3JrV3JXbUplWVZsSElrS2hPTWZWcXNMb1FkeDNJcXZsNWpLMWg2elc3QzcyeG1OdUUwVGotbEM1ZTA4VmMtU0JWMUFKV3R4T0JmRUVvNnFwZXhpVDRYWWlSMXhvamJfeHBKWjdXQTUxQl9jU0c1UWJDVFpHZGZvcm8zc3oxYWVyeDMzUUFkdVpoRXR6ZEJ0SzN6SERLaWd6dERQY0RXTzViLThpR0dzY05tX2ZqNU9oWXRnTlBzbGtKNERoQkNOVHFKY1V0OTVLeDZUUmstSk9saW9tNTFnZUYwSkJBMk5HQnU0UXlzMFpyY2M0V1hTUWM3RU5FeDY2d0FJc1RpSFk1clVPNzRqTHF2YUYzOENMek5mak1HYlFFWVYwaFBnZw==","email":"mhildenb@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkrZg456xBT6EhJoeCB55Ozqh/qjOqBgYOYyrLQicegHre9wrtH6xemXHTxWEU3G4vpkjYGSJVAZwJxsitLegWnMlZzSU635vrwtr09ffKmadSMP1Jqn52xTPCrgC2jEZb+11stRjQ4JfC67gFu4W1TPOyd0tRUu++rdjHK213urga7lUMjgfcmf+eGH9MiU+2mYnHvT6uR8d6i4iW0mYPUBWn085KIxOIDXDjUVWi4/Tnltw5QnlHJT4wG25NpxkCUftt83N9wae1CCOVR6i3IhGVmcpZJ8gwedhTF6OtMyGFrRm7mYDw8vOqcPD5OwFbnCVxGmr8nfEGq74NSC/1EvgZVKJVsEPZUP6lJTFTk3svVQbHVJ6kXQpXMLglFWaqtAHvWCRnd0INyub0Yc/7RSRf2mAcKGHNOof8kVnTXwltrgJk3TJUjac9udfB1C5wM4yxiIdsDjllcomShE/Db/DTkBc8Zl/cQwRjsWIm1gxzVIpQ/TIJeM+8xqEPaXc= marc.hildenbrand@MacBook-Pro
